# ================= LINUX FILE PATHS =================

gstr1.file.location=/u01/Incoming/json/server/gstr1/
gstr1A.file.location=/u01/Incoming/json/server/gstr1A/
gstr2b.file.location=/u01/Incoming/json/server/gstr2b/
gstr3b.file.location=/u01/Incoming/json/server/gstr3b/
gstr4.file.location=/u01/Incoming/json/server/gstr4/
gstr5.file.location=/u01/Incoming/json/server/gstr5/
gstr6.file.location=/u01/Incoming/json/server/gstr6/
gstr7.file.location=/u01/Incoming/json/server/gstr7/
gstr8.file.location=/u01/Incoming/json/server/gstr8/
gstr9.file.location=/u01/Incoming/json/server/gstr9/
gstr9a.file.location=/u01/Incoming/json/server/gstr9a/
gstr9c.file.location=/u01/Incoming/json/server/gstr9c/
gstr98a.file.location=/u01/Incoming/json/server/gstr98a/
gstr10.file.location=/u01/Incoming/json/server/gstr10/
cmp8.file.location=/u01/Incoming/json/server/cmp08/
pmt.file.location=/u01/Incoming/json/server/pmt/
gstr5a.file.location=/u01/Incoming/json/server/gstr5a/

itc2.file.location=/u01/Incoming/json/server/itc02/
gstr2.file.location=/u01/Incoming/json/server/gstr2/
gstr3.file.location=/u01/Incoming/json/server/gstr3/
gstr11.file.location=/u01/Incoming/json/server/gstr11/
gstr1r3b.file.location=/u01/Incoming/json/server/gstr1r3b/





payment.file.location=/u01/Incoming/json/server/payment/

search-tax.payer.file.location=/u01/Incoming/json/server/searchTaxPayer/
normal-compostion.file.location=/u01/Incoming/json/server/regis/
ledger.file.location=/u01/Incoming/json/server/ledger/
json-file-path-normal-compostion.file.location=/u01/Incoming/json/server/composition/
tds-tcs.file.location=/u01/Incoming/json/server/tdstcs/
file.dir.adjudication=/u01/Incoming/json/server/adjudication/
document.file.location=/u01/Incoming/json/server/registractionDocument/
file.dir.enforcement=/u01/Incoming/json/server/enforcement/

file.dir=/u01/Incoming/json/server/gstr2a/

#ewayBill.file.gz.file=/u01/Incoming/json/server/ewaybill/
ewayBill.file.location=/u01/Incoming/json/eway/

extraction.source-folder-eway-bill=/u01/Incoming/json/server/ewaybill/
extraction.target-folder-eway-bill=/u01/Incoming/json/server/ewaybill/
extraction.source-folder-name-eway-bill=/u01/Incoming/json/server/ewaybill/



ewayBill.file.gz.file=/u01/Incoming/json/server/ewaybill/
ewayBill.file.gz.file.extracted=extracted

ewayBill.file.count=/u01/Incoming/json/server/ewaybill/

ledger.processing.threads=10



LOG_DIR=/u01/Incoming/logs

Arn.file.location=/u01/Incoming/json/server/ewaybill/


